PetMeWeb/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetMeWeb.Models.Siniflar;
namespace PetMeWeb.Controllers
{
    public class AboutController : Controller
    {
        // GET: About

        Context c = new Context();
        public ActionResult Index()
        {

            var degerler = c.Hakkimizdas.ToList();

            return View(degerler);
        }
    }
}

PetMeWeb/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="#" class="w3-bar-item w3-button">Sahiplendirme</a>
        <a href="/Admin/Index" class="w3-bar-item w3-button">Kayıp İlanlar </a>
        <a href="#" class="w3-bar-item w3-button">Kayıp Buldum</a>
        <a href="/Main/Index" class="w3-bar-item w3-button">Siteye Git</a>
        <a href="/Login/LogOut" class="w3-bar-item w3-button">Çıkış Yap</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15% " >

        <div class="w3-container w3-teal">
            <h2>Admin Yönetim Paneli</h2>
        </div>

       

        <div class="w3-container">
    @RenderBody()
        </div>

    </div>

</body>
</html>

PetMeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PetMeWeb/Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
    <title> PET ME </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/responsiveslides.min.js"></script>

    <script>
    // You can also use "$(window).load(function() {"
    $(function () {
      // Slideshow 1
      $("#slider1").responsiveSlides({
         auto: true,
		 nav: true,
		 speed: 500,
		 namespace: "callbacks",
      });
    });
    </script>
</head>
<body>
    <div class="header">
        <div class="wrap">
            <div class="logo"><a href="index.html"><img src="~/images/PicsArt_01-16-04.19.15.png" alt="" /></a></div>
            <div class="con-right">
                
                
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="header-bottom">
        <div class="wrap">
            <ul id="nav">
                <li><a href="/Main/Index">Anasayfa</a></li>
                <li><a class="hsubs" href="/About/Index">Hakkımızda</a></li>
                <li>
                    <a class="hsubs" href="#">İlanlar</a>
                    <ul class="subs">
                        <li><a href="/Kayip/DostumKayip">Dostum Kayıp</a></li>
                        <li><a href="/Sahiplendirme/Sahiplendirme">Sahiplendirme</a></li>
                        <li><a href="/Buldum/KayipBuldum">Kayıp Buldum</a></li>
                    </ul>
                </li>
                <li><a class="hsubs" href="/Bilgiler/Bilgiler">Yararlı Bilgiler</a></li>
                <li><a href="/Login/Login">Giriş</a></li>

            </ul>
        </div>
    </div>
    
    <div class"content">
        @RenderBody()
    </div>
    <div class="footer-bottom">
        <div class="wrap">
            <div class="bilgi">
                <p> 2020/2021 İleri Web Dönem Projesidir </p>
            </div>
        </div>
    </div>
</body>
</html>